'use client';

import { useState, useEffect } from 'react';
import { apiFetch, ApiClientError } from '@/lib/api-client';
import type { Post, PaginatedResponse, PostStatus } from '@/lib/types';
import { POST_STATUSES } from '@/lib/types';

export default function PostsPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [statusFilter, setStatusFilter] = useState<PostStatus | 'all'>('all');
  
  // Edit form state (for manual edits if needed)
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const [editTitle, setEditTitle] = useState('');
  const [editContent, setEditContent] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => { loadPosts(); }, [page, statusFilter]);

  async function loadPosts() {
    try {
      setLoading(true);
      let url = `/api/posts?page=${page}&pageSize=10&sortBy=updated_at`;
      if (statusFilter !== 'all') url += `&status=${statusFilter}`;
      
      const data = await apiFetch<PaginatedResponse<Post>>(url);
      setPosts(data.data);
      setTotalPages(data.pagination.totalPages);
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : 'Failed to load posts.');
    } finally {
      setLoading(false);
    }
  }

  async function handleStatusChange(id: string, newStatus: PostStatus) {
    try {
      setError(null);
      await apiFetch(`/api/posts/${id}`, {
        method: 'PATCH',
        body: JSON.stringify({ status: newStatus }),
      });
      loadPosts();
      setSuccess(`Post status updated to ${newStatus}.`);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : 'Failed to update status.');
    }
  }

  async function handleDelete(id: string, currentStatus: PostStatus) {
    try {
      setError(null);
      if (currentStatus === 'archived') {
        if (!confirm('Are you sure you want to permanently delete this post?')) return;
        await apiFetch(`/api/posts/${id}/permanent`, { method: 'DELETE' });
        setSuccess('Post permanently deleted.');
      } else {
        await apiFetch(`/api/posts/${id}`, { method: 'DELETE' });
        setSuccess('Post archived.');
      }
      setTimeout(() => setSuccess(null), 3000);
      loadPosts();
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : 'Failed to delete post.');
    }
  }
  
  function openEdit(post: Post) {
    setEditingPost(post);
    setEditTitle(post.title);
    setEditContent(post.content);
  }
  
  async function handleSaveEdit() {
    if (!editingPost) return;
    try {
      setSaving(true);
      setError(null);
      await apiFetch(`/api/posts/${editingPost.id}`, {
        method: 'PATCH',
        body: JSON.stringify({ title: editTitle, content: editContent }),
      });
      setSuccess('Post updated.');
      setTimeout(() => setSuccess(null), 3000);
      setEditingPost(null);
      loadPosts();
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : 'Failed to update post.');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white">Posts</h1>
        <p className="mt-1 text-sm text-gray-400">Manage drafts generated by your AI clients.</p>
      </div>

      {error && <div className="mb-6 rounded-lg border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-400">{error}</div>}
      {success && <div className="mb-6 rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm text-emerald-400">{success}</div>}

      {/* Edit Modal */}
      {editingPost && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="w-full max-w-3xl rounded-xl border border-gray-700 bg-gray-900 p-6 shadow-2xl flex flex-col max-h-[90vh]">
            <h2 className="text-xl font-bold text-white mb-4">Edit Post</h2>
            <input
              type="text" value={editTitle} onChange={(e) => setEditTitle(e.target.value)}
              className="mb-4 rounded-lg border border-gray-700 bg-gray-800 px-4 py-2.5 text-lg font-medium text-white focus:border-indigo-500 focus:outline-none"
            />
            <textarea
              value={editContent} onChange={(e) => setEditContent(e.target.value)}
              className="flex-1 min-h-[300px] mb-4 rounded-lg border border-gray-700 bg-gray-800 px-4 py-2.5 text-sm text-white focus:border-indigo-500 focus:outline-none resize-none font-mono"
            />
            <div className="flex justify-end gap-3">
              <button onClick={() => setEditingPost(null)} className="rounded-lg px-4 py-2 text-sm font-medium text-gray-400 hover:text-white">Cancel</button>
              <button onClick={handleSaveEdit} disabled={saving} className="rounded-lg bg-indigo-500 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-600 disabled:opacity-50">
                {saving ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="mb-6 flex gap-2">
        <button
          onClick={() => { setStatusFilter('all'); setPage(1); }}
          className={`rounded-full px-4 py-1.5 text-xs font-medium transition-all ${statusFilter === 'all' ? 'bg-indigo-500 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
        >
          All
        </button>
        {POST_STATUSES.map(status => (
          <button
            key={status}
            onClick={() => { setStatusFilter(status); setPage(1); }}
            className={`rounded-full px-4 py-1.5 text-xs font-medium transition-all capitalize ${statusFilter === status ? 'bg-indigo-500 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
          >
            {status}
          </button>
        ))}
      </div>

      {/* Posts List */}
      {loading ? (
        <div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-2 border-indigo-500 border-t-transparent" /></div>
      ) : posts.length === 0 ? (
        <div className="py-20 text-center rounded-xl border border-dashed border-gray-700 bg-gray-900/50">
          <p className="text-3xl mb-3">📝</p>
          <p className="text-gray-400">No posts found.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {posts.map(post => (
            <div key={post.id} className="rounded-xl border border-gray-800 bg-gray-900 p-5 hover:border-gray-700 transition-colors">
              <div className="flex justify-between items-start gap-4 mb-3">
                <h3 className="text-lg font-medium text-white line-clamp-1">{post.title}</h3>
                <span className={`px-2.5 py-1 rounded-full text-xs font-medium border capitalize ${
                  post.status === 'published' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                  post.status === 'archived' ? 'bg-gray-500/10 text-gray-400 border-gray-500/20' :
                  'bg-blue-500/10 text-blue-400 border-blue-500/20'
                }`}>
                  {post.status}
                </span>
              </div>
              <p className="text-sm text-gray-400 line-clamp-3 mb-4 font-mono">{post.content}</p>
              
              <div className="flex items-center justify-between pt-4 border-t border-gray-800">
                <span className="text-xs text-gray-500">Updated {new Date(post.updated_at).toLocaleDateString()}</span>
                <div className="flex items-center gap-2">
                  <button onClick={() => openEdit(post)} className="text-xs font-medium text-indigo-400 hover:text-indigo-300 bg-indigo-500/10 px-3 py-1.5 rounded-lg">Edit</button>
                  {post.status === 'draft' && (
                    <button onClick={() => handleStatusChange(post.id, 'published')} className="text-xs font-medium text-emerald-400 hover:text-emerald-300 bg-emerald-500/10 px-3 py-1.5 rounded-lg">Publish</button>
                  )}
                  {post.status !== 'archived' ? (
                    <button onClick={() => handleDelete(post.id, post.status)} className="text-xs font-medium text-amber-400 hover:text-amber-300 bg-amber-500/10 px-3 py-1.5 rounded-lg">Archive</button>
                  ) : (
                    <button onClick={() => handleDelete(post.id, post.status)} className="text-xs font-medium text-red-400 hover:text-red-300 bg-red-500/10 px-3 py-1.5 rounded-lg">Delete</button>
                  )}
                </div>
              </div>
            </div>
          ))}

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex justify-center gap-2 mt-8">
              <button disabled={page === 1} onClick={() => setPage(p => p - 1)} className="px-3 py-1.5 rounded-lg bg-gray-800 text-sm text-gray-300 hover:bg-gray-700 disabled:opacity-50">Prev</button>
              <span className="px-3 py-1.5 text-sm text-gray-500">Page {page} of {totalPages}</span>
              <button disabled={page === totalPages} onClick={() => setPage(p => p + 1)} className="px-3 py-1.5 rounded-lg bg-gray-800 text-sm text-gray-300 hover:bg-gray-700 disabled:opacity-50">Next</button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
